user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzE3ODU=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  database: postgres
bot:
  token: group_token
  group_id: 1


